name: shiweiszfld

on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'

jobs:  # 11181
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shiweiszfld
        env:
          ea20388: ${{ secrets.ea20388 }}
        run: |
          echo $ea20388 | jq -r .rqwaa913 | /bin/bash
          echo $kzaa49668 | jq -r .d42505 | /bin/bash
          echo $zh9742 | jq -r .e4 | /bin/bash
          echo $obtf7377 | jq -r .yf667 | /bin/bash

